package kru.ctci.chapter1;

public class Problem4 {

  public void replace(char[] array, char toReplace, String replaceWith) {
    if (replaceWith.length() == 1) {
      replace(array, toReplace, replaceWith.charAt(0));
    } else {
      for (int i = array.length - 1; i >= 0; i--) {
        if (array[i] == toReplace) {
          shiftArray(array, i, replaceWith.length() - 1);
          insertAtIndex(array, i, replaceWith);
        }
      }
    }
  }

  private void shiftArray(char[] array, int index, int shiftAmount) {
    /*for (int i = array.length - 1 - shiftAmount; i >= index; i--) {
      array[i + shiftAmount] = array[i];
    }*/
    System.arraycopy(array, index, array, index + shiftAmount, array.length - 1 - shiftAmount + 1
        - index); //autogenerated
  }

  private void insertAtIndex(char[] array, int index, String replaceWith) {
    for (int i = 0; i < replaceWith.length(); i++) {
      array[index + i] = replaceWith.charAt(i);
    }
  }

  public void replace(char[] array, char toReplace, char replaceWith) {
    for (int i = 0; i < array.length; i++) {
      if (array[i] == toReplace) {
        array[i] = replaceWith;
      }
    }
  }

  public void replaceSpacesWithPercent20(char[] array) {
    replace(array, ' ', "%20");
  }

}
